# -*- coding: utf-8 -*-
"""STA301_S25_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXVBd8tGotPVF2cTLpmo_aV7--DIWzBt

READ FILE
"""

#installs
install.packages("viridis")
install.packages("Amelia")
install.packages("e1071")
install.packages("caret")
install.packages("car")
install.packages("naivebayes")

#library
library(dplyr)
library(purrr)
library(tibble)
library(ggplot2)
library(viridis)
library(Amelia)
library(rlang)
library(e1071)
library(caret)
library(car)
library(naivebayes)
library(ggplot2)

set.seed(87698) # ID sampling for consistency
#read file
#make sure data file is read well => header adjustment
data <- read.csv("rideshare_kaggle.csv", header=FALSE, skip=1)
header <- read.csv("rideshare_kaggle.csv", header = FALSE, nrows = 1)
#data
head(data)

View(header)

# match header to data
colnames(data) <- header

glimpse(data)

View(data)

"""LIBRARY LOADING

## PREPROCESSING

SUMMARY & DESCRIPTION
"""

# Summary and Description

# function for general stats (skips the non-numerical values )
get_stats <- function(x) {
  if (is.numeric(x)) {
    tibble::tibble(
      Mean = mean(x, na.rm = TRUE),
      Median_Q2 = median(x, na.rm = TRUE),
      Mode = as.character(names(sort(table(x), decreasing = TRUE)[1])),
      SD = sd(x, na.rm = TRUE),
      Min = min(x, na.rm = TRUE),
      Q1 = quantile(x, 0.25, na.rm = TRUE),
      Q3 = quantile(x, 0.75, na.rm = TRUE),
      Max = max(x, na.rm = TRUE)
    )
  } else {
    tibble::tibble(
      Mean = NA, Median_Q2 = NA, Mode = NA,
      SD = NA, Min = NA, Q1 = NA, Q3 = NA, Max = NA
    )
  }
}

# apply function
summary_df <- purrr::map_dfr(data, get_stats, .id = "Variable")

# print summary table
print(summary_df)

#summary table
View(summary_df)

#entire dataset
glimpse(data)

# count of missing values in each feature
missing_data_summary <- sapply(data, function(x) sum(is.na(x)))

#missing value table
missing_data_summary_table <- tibble(
  Variable = names(data),
  Missing_Count = missing_data_summary,
  Missing_Percentage = missing_data_summary / nrow(data) * 100
)

View(missing_data_summary_table)

# create cleaned data
cleaned_data <- data %>% filter(!is.na(price))

# data structure
glimpse(cleaned_data)

#double check the missing values
missing_data_summary <- sapply(cleaned_data, function(x) sum(is.na(x)))

#a summary table with the proportion of missing values
missing_data_summary_table <- tibble(
  Variable = names(cleaned_data),
  Missing_Count = missing_data_summary,
  Missing_Percentage = missing_data_summary / nrow(data) * 100
)

View(missing_data_summary_table)

# check for na one final time
invalid_columns <- sapply(cleaned_data, function(col) all(is.na(col)))
print(names(cleaned_data)[invalid_columns])

#general
inva_cols <- sapply(cleaned_data, function(col) any(is.nan(col) | is.infinite(col)))
names(cleaned_data)[inva_cols]

summary(cleaned_data)

#check which column has NaNs
# NA values in the dataset
cat("Total number of NA values in the dataset:", sum(is.na(cleaned_data)), "\n")

# NaN values in the dataset
cat("Total number of NaN values in the dataset:", sum(sapply(cleaned_data, function(col) sum(is.nan(col)))), "\n")

# infinite values in the dataset
cat("Total number of infinite values in the dataset:", sum(sapply(cleaned_data, function(col) sum(is.infinite(col)))), "\n")

"""Additional Feature Selection & Cleaning"""

#Additional Cleaning (feature reduction based on logic)
#unique values => id,timestamp
#same value => time zone
#super specfic for general/stable conclusion => datetime removal
#time related features removal => ex. temperatureHighTime, temperatureLowTime, apparentTemperatureHighTime, apparentTemperatureLowTime


columns_to_remove <- c(
  "id",
  "timestamp",
  "datetime",
  "timezone",
  "product_id",
  "temperatureHighTime",
  "temperatureLowTime",
  "apparentTemperatureHighTime",
  "apparentTemperatureLowTime",
  "visibility.1",
  "uvIndexTime",
  "temperatureMinTime",
  "temperatureMaxTime",
  "apparentTemperatureMinTime",
  "windGustTime",
  "apparentTemperatureMaxTime"
)

# Remove them from the data
cleaned_data <- cleaned_data[, !(names(cleaned_data) %in% columns_to_remove)]

#View(cleaned_data)
glimpse(cleaned_data)

"""OUTLIERS"""

#this took so long to run => will do a focused version
# visualize outliers rather than eliminate them
#reason? we want to observe how the price changes in extreme weather situations for example

# find outliers based on IQR method (on the cleaned data thus recalc)

# only numeric columns
numeric_data <- cleaned_data[, sapply(cleaned_data, is.numeric)]
#numeric_data[] <- lapply(numeric_data, as.numeric) # convert all columns to numeric

# compute IQR
Q1 <- apply(numeric_data, 2, function(x) quantile(x, 0.25, na.rm = TRUE))
Q3 <- apply(numeric_data, 2, function(x) quantile(x, 0.75, na.rm = TRUE))
IQR_values <- Q3 - Q1

# outliers
outliers <- lapply(names(numeric_data), function(col) {
  x <- numeric_data[[col]]
  lower_bound <- Q1[col] - 1.5 * IQR_values[col]
  upper_bound <- Q3[col] + 1.5 * IQR_values[col]
  which(x < lower_bound | x > upper_bound)
})
names(outliers) <- names(numeric_data)

# View outliers per column (row indices)
outliers

# number of outliers per feature
outlier_counts <- sapply(outliers, length)

#  summary table
outlier_summary_table <- tibble::tibble(
  Feature = names(outlier_counts),
  Outlier_Count = outlier_counts,
  Outlier_Percentage = round(outlier_counts / nrow(cleaned_data) * 100, 2)
)


View(outlier_summary_table)

#focused version

cols_of_interest <- c("price", "temperature", "windSpeed", "precipIntensity")

numeric_data <- cleaned_data[, cols_of_interest, drop = FALSE]

Q1 <- apply(numeric_data, 2, function(x) quantile(x, 0.25, na.rm = TRUE))
Q3 <- apply(numeric_data, 2, function(x) quantile(x, 0.75, na.rm = TRUE))
IQR_values <- Q3 - Q1

outliers <- lapply(names(numeric_data), function(col) {
  x <- numeric_data[[col]]
  lower_bound <- Q1[col] - 1.5 * IQR_values[col]
  upper_bound <- Q3[col] + 1.5 * IQR_values[col]
  which(x < lower_bound | x > upper_bound)
})
names(outliers) <- names(numeric_data)

# result => not really meaningful
outliers

#get column names
names(cleaned_data)

# unique values per column
unique_counts <- sapply(cleaned_data, function(col) length(unique(col)))

# data frame for display
unique_counts_df <- data.frame(
  Feature = names(unique_counts),
  Unique_Values = as.vector(unique_counts)
)

# sorted descending
unique_counts_df <- unique_counts_df[order(-unique_counts_df$Unique_Values), ]
print(unique_counts_df, row.names = FALSE)

str(cleaned_data$windGust)

#note that numeric and integer are treated the same and the only difference is memory related => thus will be left the same.
# Get the class/type of each feature (column) in the data frame
feature_types <- sapply(cleaned_data, class)

# Convert to a data frame for easier viewing
feature_types_df <- data.frame(
  Feature = names(feature_types),
  Type = as.vector(feature_types)
)

# Display the table
print(feature_types_df, row.names = FALSE)

#get column names:
names(cleaned_data)

# Your selected features => removed categorical
target_cols <- c('hour', 'day', 'month', 'price', 'distance',
                 'surge_multiplier', 'latitude', 'longitude',
                 'temperature', 'apparentTemperature')

# convert them to numeric
for (col in target_cols) {
  if (col %in% names(cleaned_data)) {
    cleaned_data[[col]] <- suppressWarnings(as.numeric(cleaned_data[[col]]))
  } else {
    warning(paste("Column", col, "not found in data."))
  }
}

# only the specified numeric-converted columns
numeric_data <- cleaned_data[, target_cols]

# Box plot visualization
for (col in names(numeric_data)) {
  try({
    data_to_plot <- na.omit(numeric_data[[col]])

    if (length(data_to_plot) > 0) {
      boxplot(data_to_plot,
              main = col,
              col = "skyblue",
              outline = TRUE,
              na.rm = TRUE)
      Sys.sleep(2)
    } else {
      warning(paste("Skipping column", col, "because it has no valid numeric data."))
    }
  }, silent = TRUE)
}

# new target features
target_cols <- c('precipIntensity', 'precipProbability', 'humidity',
                 'windSpeed', 'windGust', 'visibility',
                 'temperatureHigh',
                 'temperatureLow',
                 'apparentTemperatureHigh',
                 'apparentTemperatureLow',
                 'dewPoint', 'pressure', 'windBearing',
                 'cloudCover', 'uvIndex',  'ozone')


for (col in target_cols) {
  if (col %in% names(cleaned_data)) {

    if (is.integer(cleaned_data[[col]])) {

      cleaned_data[[col]] <- as.numeric(cleaned_data[[col]])
    }
  } else {
    warning(paste("Column", col, "not found in data."))
  }
}


numeric_data <- cleaned_data[, target_cols]

for (col in names(numeric_data)) {
  try({
    data_to_plot <- na.omit(numeric_data[[col]])

    if (length(data_to_plot) > 0) {
      boxplot(data_to_plot,
              main = col,
              col = "skyblue",
              outline = TRUE,
              na.rm = TRUE)
      Sys.sleep(2)  # plot pause
    } else {
      warning(paste("Skipping column", col, "because it has no valid numeric data."))
    }
  }, silent = TRUE)
}

target_cols <- c("sunriseTime", "sunsetTime", "moonPhase", "precipIntensityMax",
                 "temperatureMin", "temperatureMax",
                 "apparentTemperatureMin", "apparentTemperatureMax")


for (col in target_cols) {
  if (col %in% names(cleaned_data)) {

    if (is.integer(cleaned_data[[col]])) {

      cleaned_data[[col]] <- as.numeric(cleaned_data[[col]])
    }
  } else {
    warning(paste("Column", col, "not found in data."))
  }
}


numeric_data <- cleaned_data[, target_cols]


for (col in names(numeric_data)) {
  try({
    data_to_plot <- na.omit(numeric_data[[col]])

    if (length(data_to_plot) > 0) {
      boxplot(data_to_plot,
              main = col,
              col = "skyblue",
              outline = TRUE,
              na.rm = TRUE)
      Sys.sleep(2)  # plot pause
    } else {
      warning(paste("Skipping column", col, "because it has no valid numeric data."))
    }
  }, silent = TRUE)
}

#note that numeric and integer are treated the same and the only difference is memory related => thus will be left the same.
# the type of each feature
feature_types <- sapply(cleaned_data, class)

# df
feature_types_df <- data.frame(
  Feature = names(feature_types),
  Type = as.vector(feature_types)
)


print(feature_types_df, row.names = FALSE)

"""SAMPLING"""

cleaned_data$combined <- paste(cleaned_data$month, cleaned_data$day, cleaned_data$hour, sep = "-")

# print the updated rideshare data frame
print(cleaned_data$combined)

# set the sample size X
X <- 250

# create a new empty data frame to store the equal samples
equal_samples_df <- data.frame()

# get the unique values of the 'combined' column
unique_combined_values <- unique(cleaned_data$combined)

# loop through each unique 'combined' value and sample
for (value in unique_combined_values) {
  # subset the data for the current 'combined' value
  subset_data <- cleaned_data[cleaned_data$combined == value, ]

  # if the group has more than X samples => sample X observations
  if (nrow(subset_data) > X) {
    sampled_data <- subset_data[sample(1:nrow(subset_data), X), ]
  } else {
    # if not => take all the samples from that group
    sampled_data <- subset_data
  }

  # append the sampled data to the new df
  equal_samples_df <- rbind(equal_samples_df, sampled_data)
}

# print the new dataset with equal samples
print(equal_samples_df)

# frequency table for the new sampled dataset
freq_table_sampled <- table(equal_samples_df$combined)

# print the frequency table of the sampled dataset
print(freq_table_sampled)


# get the frequencies of the frequencies
freq_of_freqs <- table(freq_table_sampled)

# print the frequency of frequencies
print(freq_of_freqs)

"""## EDA

UNIVAR
"""

# variability for numerical columns
# filter numeric/integer columns
numeric_cols <- sapply(cleaned_data, function(col) is.numeric(col) || is.integer(col))
numeric_data <- cleaned_data[, numeric_cols]
# empty df
variability_df <- data.frame(
  Feature = character(),
  Min = numeric(),
  Max = numeric(),
  Range = numeric(),
  Variance = numeric(),
  SD = numeric(),
  stringsAsFactors = FALSE
)


for (col_name in names(numeric_data)) {
  col_data <- numeric_data[[col_name]]
  col_data_clean <- na.omit(col_data)

  # skip columns with all NA values => for saftey
  if (length(col_data_clean) == 0) next

  variability_df <- rbind(variability_df, data.frame(
    Feature = col_name,
    Min = min(col_data_clean),
    Max = max(col_data_clean),
    Range = max(col_data_clean) - min(col_data_clean),
    Variance = var(col_data_clean),
    SD = sd(col_data_clean)
  ))
}


View(variability_df)

View(cleaned_data)

selected_features_1 <- c('hour','day','month','source','destination','cab_type','name','price','distance',
                         'surge_multiplier','latitude','longitude','temperature','apparentTemperature',
                         'short_summary','long_summary','precipIntensity','precipProbability','humidity',
                         'windSpeed','windGust')
for (col_name in selected_features_1) {
  if (!col_name %in% names(cleaned_data)) {
    cat("Column", col_name, "not found in data.\n")
    next
  }

  col_data <- cleaned_data[[col_name]]

  # Skip non-numeric or empty columns safely
  if (!is.numeric(col_data)) {
    cat("Skipping non-numeric column:", col_name, "\n")
    next
  }

  col_data <- na.omit(col_data)

  if (length(col_data) < 2) {
    cat("Skipping column with insufficient numeric data/categorical data:", col_name, "\n")
    next
  }

  par(mfrow = c(1, 3))

  tryCatch({
    hist(col_data, main = paste("Histogram of", col_name), col = "skyblue", xlab = col_name)
  }, error = function(e) {
    cat("  Error in histogram for", col_name, ":", e$message, "\n")
    plot.new(); title("Histogram error")
  })

  tryCatch({
    boxplot(col_data, main = paste("Boxplot of", col_name), col = "orange")
  }, error = function(e) {
    cat("  Error in boxplot for", col_name, ":", e$message, "\n")
    plot.new(); title("Boxplot error")
  })

  tryCatch({
    dens <- density(col_data, na.rm = TRUE)
    if (length(dens$x) > 1) {
      plot(dens, main = paste("Density of", col_name))
    } else {
      cat("  Not enough data for density plot of", col_name, "\n")
      plot.new(); title("Density insufficient")
    }
  }, error = function(e) {
    cat("  Error in density plot for", col_name, ":", e$message, "\n")
    plot.new(); title("Density error")
  })

  cat("\nProcessed numeric feature:", col_name, "\n")
  par(mfrow = c(1, 1))
}

selected_features_2 <- c('visibility','temperatureHigh','temperatureLow','apparentTemperatureHigh',
                         'apparentTemperatureLow','icon','dewPoint','pressure','windBearing',
                         'cloudCover','uvIndex','ozone')

for (col_name in selected_features_2) {
  if (!col_name %in% names(cleaned_data)) {
    cat("Column", col_name, "not found in data.\n")
    next
  }

  col_data <- cleaned_data[[col_name]]

  # skip non-numeric/empty
  if (!is.numeric(col_data)) {
    cat("Skipping non-numeric column:", col_name, "\n")
    next
  }

  col_data <- na.omit(col_data)

  if (length(col_data) < 2) {
    cat("Skipping column with insufficient numeric data/categorical data:", col_name, "\n")
    next
  }

  par(mfrow = c(1, 3))

  tryCatch({
    hist(col_data, main = paste("Histogram of", col_name), col = "skyblue", xlab = col_name)
  }, error = function(e) {
    cat("  Error in histogram for", col_name, ":", e$message, "\n")
    plot.new(); title("Histogram error")
  })

  tryCatch({
    boxplot(col_data, main = paste("Boxplot of", col_name), col = "orange")
  }, error = function(e) {
    cat("  Error in boxplot for", col_name, ":", e$message, "\n")
    plot.new(); title("Boxplot error")
  })

  tryCatch({
    dens <- density(col_data, na.rm = TRUE)
    if (length(dens$x) > 1) {
      plot(dens, main = paste("Density of", col_name))
    } else {
      cat("  Not enough data for density plot of", col_name, "\n")
      plot.new(); title("Density insufficient")
    }
  }, error = function(e) {
    cat("  Error in density plot for", col_name, ":", e$message, "\n")
    plot.new(); title("Density error")
  })

  cat("\nProcessed numeric feature:", col_name, "\n")
  par(mfrow = c(1, 1))
}

selected_features_3 <- c('moonPhase','precipIntensityMax',
                         'temperatureMin','temperatureMax','apparentTemperatureMin','apparentTemperatureMax')

for (col_name in selected_features_3) {
  if (!col_name %in% names(cleaned_data)) next

  col_data <- cleaned_data[[col_name]]

  # Check if column is numeric
  if (!is.numeric(col_data)) {
    cat("Skipping non-numeric column:", col_name, "\n")
    next
  }

  par(mfrow = c(1, 3))

  tryCatch({
    hist(col_data, main = paste("Histogram of", col_name), col = "skyblue", xlab = col_name)
  }, error = function(e) {
    cat("  Error in histogram for", col_name, ":", e$message, "\n")
    plot.new(); title("Histogram error")
  })

  tryCatch({
    boxplot(col_data, main = paste("Boxplot of", col_name), col = "orange")
  }, error = function(e) {
    cat("  Error in boxplot for", col_name, ":", e$message, "\n")
    plot.new(); title("Boxplot error")
  })

  tryCatch({
    dens <- density(col_data, na.rm = TRUE)
    if (length(dens$x) > 1) {
      plot(dens, main = paste("Density of", col_name))
    } else {
      cat("  Not enough data for density plot of", col_name, "\n")
      plot.new(); title("Density insufficient")
    }
  }, error = function(e) {
    cat("  Error in density plot for", col_name, ":", e$message, "\n")
    plot.new(); title("Density error")
  })
   cat("\nProcessing numeric feature:", col_name, "\n")
  par(mfrow = c(1, 1))
}

#range issues but print despite errors
selected_features_3 <- c('sunriseTime','sunsetTime')

for (col_name in selected_features_3) {
  if (!col_name %in% names(cleaned_data)) next

  col_data <- cleaned_data[[col_name]]

  # check numeric
  if (!is.numeric(col_data)) {
    cat("Skipping non-numeric column:", col_name, "\n")
    next
  }

  par(mfrow = c(1, 3))

  tryCatch({
    hist(col_data, main = paste("Histogram of", col_name), col = "skyblue", xlab = col_name)
  }, error = function(e) {
    cat("  Error in histogram for", col_name, ":", e$message, "\n")
    plot.new(); title("Histogram error")
  })

  tryCatch({
    boxplot(col_data, main = paste("Boxplot of", col_name), col = "orange")
  }, error = function(e) {
    cat("  Error in boxplot for", col_name, ":", e$message, "\n")
    plot.new(); title("Boxplot error")
  })

  tryCatch({
    dens <- density(col_data, na.rm = TRUE)
    if (length(dens$x) > 1) {
      plot(dens, main = paste("Density of", col_name))
    } else {
      cat("  Not enough data for density plot of", col_name, "\n")
      plot.new(); title("Density insufficient")
    }
  }, error = function(e) {
    cat("  Error in density plot for", col_name, ":", e$message, "\n")
    plot.new(); title("Density error")
  })
   cat("\nProcessing numeric feature:", col_name, "\n")
  par(mfrow = c(1, 1))
}

# values in the 'windGust' column
head(cleaned_data)

# dubugging check data type
typeof(cleaned_data$source)

#  selected categorical features
selected_categorical_features <- c('source', 'destination', 'cab_type', 'name', 'short_summary', 'long_summary', 'icon')

# chack type
types <- sapply(cleaned_data[, selected_categorical_features], function(x) typeof(x))

print(types)

# label wrapping
wrap_labels <- function(labels, width = 20) {
  sapply(labels, function(label) {
    paste(strwrap(label, width = width), collapse = "\n")
  })
}

# categorical features to visualize
selected_categorical_features <- c('source','destination','cab_type','name','short_summary',
                                   'long_summary','icon')

for (col_name in selected_categorical_features) {
  if (!(col_name %in% names(cleaned_data))) {
    cat("\nSkipping", col_name, "- not found in data.\n")
    next
  }

  col_data <- cleaned_data[[col_name]]

  if (is.numeric(col_data)) {
    cat("Skipping numeric column:", col_name, "\n")
    next
  }

  freq_table <- table(col_data)
  colors <- rainbow(length(freq_table))
  wrapped_labels <- wrap_labels(names(freq_table), width = 20)

  ### Bar Chart
  tryCatch({
    layout(matrix(c(1,2), nrow = 1), widths = c(3.5, 1.5))
    par(mar = c(7, 4, 4, 1))

    barplot(freq_table,
            main = paste("Bar Chart of", col_name),
            col = colors,
            xlab = "",
            ylab = "Frequency",
            names.arg = rep("", length(freq_table)),
            las = 2,
            cex.names = 0.7)

    par(mar = c(1, 0, 4, 0))
    plot.new()
    legend("center",
           legend = wrapped_labels,
           fill = colors,
           cex = 0.6,
           border = NA,
           bty = "n",
           y.intersp = 1.3)
  }, error = function(e) {
    cat("  Error in bar chart for", col_name, ":", e$message, "\n")
    plot.new(); title("Bar Chart error")
  })

  cat("\nProcessed categorical feature:", col_name, "\n")

  #Pie Chart
  tryCatch({
    percentages <- round(100 * freq_table / sum(freq_table), 1)
    pie_labels <- paste0(percentages, "%")

    layout(matrix(c(1,2), nrow = 1), widths = c(3.5, 1.5))
    par(mar = c(4, 4, 4, 1))
    pie(freq_table,
        main = paste("Pie Chart of", col_name),
        col = colors,
        labels = pie_labels)

    par(mar = c(1, 0, 4, 0))
    plot.new()
    legend("center",
           legend = wrapped_labels,
           fill = colors,
           cex = 0.6,
           border = NA,
           bty = "n",
           y.intersp = 1.3)
  }, error = function(e) {
    cat("  Error in pie chart for", col_name, ":", e$message, "\n")
    plot.new(); title("Pie Chart error")
  })

  Sys.sleep(3)
}

"""Price VS Categorical Box Plots"""

#price range
min_price <- min(cleaned_data$price, na.rm = TRUE)
max_price <- max(cleaned_data$price, na.rm = TRUE)

cat("Minimum price:", min_price, "\n")
cat("Maximum price:", max_price, "\n")

selected_categorical_features <- c('source', 'destination', 'cab_type', 'name',
                                   'short_summary', 'long_summary', 'icon')

# loop => feature vs price
for (feature in selected_categorical_features) {
  if (feature %in% names(cleaned_data)) {
    # NA check
    if (all(is.na(cleaned_data[[feature]]))) {
      cat("Skipping", feature, "because it contains only NA values.\n")
      next
    }


    p <- ggplot(cleaned_data, aes(x = .data[[feature]], y = price)) +
      geom_boxplot(outlier.color = "red", fill = "skyblue") +
      labs(title = paste("Price vs", feature), x = feature, y = "Price") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

    print(p)
    Sys.sleep(2)
  } else {
    warning(paste("Column", feature, "not found in cleaned_data."))
  }
}

"""Surge Multiplier Vs Categorical Box Plots"""

# selected categorical features
selected_categorical_features <- c('source','destination','cab_type','name',
                                   'short_summary','long_summary','icon')


for (cat_feature in selected_categorical_features) {

  if (cat_feature %in% names(cleaned_data)) {

    p <- ggplot(cleaned_data, aes(x = .data[[cat_feature]], y = surge_multiplier)) +
      geom_boxplot(fill = "skyblue", outlier.colour = "red", outlier.shape = 1) +
      labs(title = paste("Surge Multiplier vs", cat_feature),
           x = cat_feature,
           y = "Surge Multiplier") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

    print(p)
    Sys.sleep(2)
  } else {
    warning(paste("Feature", cat_feature, "not found in the dataset."))
  }
}

"""Price vs numerical variables (scatter plot)"""

#  excluding 'price'
numeric_features <- names(cleaned_data)[sapply(cleaned_data, is.numeric)]
numeric_features <- setdiff(numeric_features, "price")

for (feature in numeric_features) {
  if (all(is.na(cleaned_data[[feature]]))) {
    cat("Skipping", feature, "because it contains only NA values.\n")
    next
  }

  p <- ggplot(cleaned_data, aes(x = .data[[feature]], y = price)) +
    geom_point(alpha = 0.5, color = "steelblue") +
    labs(title = paste("Price vs", feature), x = feature, y = "Price") +
    theme_minimal()

  print(p)
  Sys.sleep(2)
}

"""Surge multiplier vs  numerical variables (scatter plot)"""

numeric_features <- names(cleaned_data)[sapply(cleaned_data, is.numeric)]
numeric_features <- setdiff(numeric_features, "surge_multiplier")


for (feature in numeric_features) {
  if (all(is.na(cleaned_data[[feature]]))) {
    cat("Skipping", feature, "because it contains only NA values.\n")
    next
  }

  p <- ggplot(cleaned_data, aes(x = .data[[feature]], y = surge_multiplier)) +
    geom_point(alpha = 0.5, color = "steelblue") +
    labs(title = paste("Surge Multiplier vs", feature), x = feature, y = "Surge Multiplier") +
    theme_minimal()

  print(p)
  Sys.sleep(2)
}

"""frequency hisotgram for numerical variables"""

numeric_features <- names(cleaned_data)[sapply(cleaned_data, is.numeric)]

for (feature in numeric_features) {
  if (all(is.na(cleaned_data[[feature]]))) {
    cat("Skipping", feature, "because it contains only NA values.\n")
    next
  }

  p <- ggplot(cleaned_data, aes(x = .data[[feature]])) +
    geom_histogram(bins = 30, fill = "skyblue", color = "black", alpha = 0.7) +
    labs(title = paste("Histogram of", feature), x = feature, y = "Frequency") +
    theme_minimal()

  print(p)
  Sys.sleep(2)
}

"""weighted average graphs?

"""

#different groupings
# define grouping and value columns
grouping_features <- c('hour', 'day', 'month',
                       'source', 'destination', 'cab_type', 'name',
                       'short_summary', 'long_summary', 'icon')

value_features <- c('price', 'distance', 'surge_multiplier',
                    'temperature', 'apparentTemperature', 'dewPoint', 'humidity',
                    'pressure', 'windSpeed', 'visibility', 'ozone', 'uvIndex',
                    'temperatureHigh', 'temperatureLow',
                    'apparentTemperatureHigh', 'apparentTemperatureLow',
                    'precipIntensity', 'precipProbability', 'cloudCover',
                    'latitude', 'longitude')

for (group_col in grouping_features) {
  if (!group_col %in% names(cleaned_data)) {
    cat("Skipping", group_col, ": not in data.\n")
    next
  }

  for (value_col in value_features) {
    if (!value_col %in% names(cleaned_data)) {
      cat("Skipping", value_col, ": not in data.\n")
      next
    }


    plot_data <- cleaned_data %>%
      select(.data[[group_col]], .data[[value_col]]) %>%
      filter(!is.na(.data[[group_col]]), !is.na(.data[[value_col]]))

    # not enugh data skip
    if (nrow(plot_data) < 2) {
      cat("Skipping", value_col, "vs", group_col, ": not enough data.\n")
      next
    }

    # average per group
    avg_data <- plot_data %>%
      group_by(.data[[group_col]]) %>%
      summarise(mean_value = mean(.data[[value_col]], na.rm = TRUE), .groups = 'drop')


    p <- ggplot(avg_data, aes(x = .data[[group_col]], y = mean_value)) +
      geom_bar(stat = "identity", fill = "skyblue") +
      labs(title = paste("Average", value_col, "by", group_col),
           x = group_col, y = paste("Average", value_col)) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

    print(p)
    Sys.sleep(2)
  }
}

"""CLASSIFICATION EXPLORATION

CAB TYPE
"""

# 'cab_type' column
cab_type_frequency <- table(cleaned_data$cab_type)


cab_type_df <- as.data.frame(cab_type_frequency)

colnames(cab_type_df) <- c("Cab Type", "Frequency")

print(cab_type_df)

"""SURGE Multiplier"""

# 'surge_multiplier' column
surge_multiplier_frequency <- table(cleaned_data$surge_multiplier)


surge_multiplier_df <- as.data.frame(surge_multiplier_frequency)

colnames(surge_multiplier_df) <- c("Surge Multiplier", "Frequency")

print(surge_multiplier_df)

# create a new column to categorize surge multipliers => 'Above 1' or '1 or Below'
cleaned_data$surge_multiplier_category <- ifelse(cleaned_data$surge_multiplier > 1, "Above 1", "1 or Below")

surge_multiplier_category_frequency <- table(cleaned_data$surge_multiplier_category)

surge_multiplier_category_df <- as.data.frame(surge_multiplier_category_frequency)

colnames(surge_multiplier_category_df) <- c("Surge Multiplier Category", "Frequency")

print(surge_multiplier_category_df)

"""Name"""

# Create a table of the frequency of each name
name_frequency <- table(cleaned_data$name)

name_frequency_df <- as.data.frame(name_frequency)

colnames(name_frequency_df) <- c("Name", "Frequency")

print(name_frequency_df)

"""BIVAR AND MULTIVAR

Covariance Matrix
"""

numeric_vars <- equal_samples_df[, sapply(equal_samples_df, is.numeric)]

cov_matrix <- cov(numeric_vars, use = "complete.obs")

print(round(cov_matrix, 2))

"""Correlation Matrix

"""

vars <- c("price", "distance", "surge_multiplier", "temperature", "pressure")
corr_data <- equal_samples_df[, vars]

cor_matrix <- cor(corr_data, use = "complete.obs")

install.packages("corrplot")
library(corrplot)

corrplot(cor_matrix, method = "color", type = "upper",
         addCoef.col = "black", tl.cex = 0.8,
         col=colorRampPalette(c("blue", "white", "red"))(200),
         number.cex = 0.8, tl.col = "black",
         title = "Correlation Matrix of Key Variables", mar=c(0,0,2,0))

"""Variation Coefficient"""

cv_calculation <- cleaned_data %>%
  group_by(cab_type) %>%
  summarise(
    mean_price = mean(price, na.rm = TRUE),
    sd_price = sd(price, na.rm = TRUE),
    cv = sd_price / mean_price
  )

print(cv_calculation)

"""Frequency Table"""

freq_table <- cleaned_data %>%
  count(cab_type, surge_multiplier) %>%
  mutate(probability = n / sum(n))

print(freq_table)

"""Time series plot"""

library(ggplot2)

set.seed(42)
n_samples <- 250
hour <- sample(0:23, n_samples, replace = TRUE)
day <- sample(1:30, n_samples, replace = TRUE)
month <- sample(1:12, n_samples, replace = TRUE)
price <- runif(n_samples, 10, 100)

data <- data.frame(hour, day, month, price)

data$datetime <- as.POSIXct(paste(2025, data$month, data$day, data$hour, sep = "-"), format = "%Y-%m-%d-%H")


data <- data[order(data$datetime), ]


ggplot(data, aes(x = datetime, y = price)) +
  geom_line(color = "blue") +
  labs(title = "Time Series Plot of Price Over Time", x = "Datetime", y = "Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

"""Probablity Distributions:

Binomial Distribution
"""

binom_data <- rbinom(1000, size = 10, prob = 0.3)
ggplot(data.frame(binom_data), aes(x = binom_data)) +
  geom_histogram(bins = 10, fill = "skyblue", color = "black") +
  labs(title = "Binomial Distribution", x = "Number of Successes", y = "Frequency") +
  theme_minimal()

"""Multinomial Distribution"""

install.packages("reshape2")
library(reshape2)
set.seed(123)
multinom_data <- t(rmultinom(1000, size = 10, prob = c(0.3, 0.5, 0.2)))
multinom_df <- as.data.frame(multinom_data)
colnames(multinom_df) <- c("A", "B", "C")
melted_multinom <- reshape2::melt(multinom_df)
ggplot(melted_multinom, aes(x = value, fill = variable)) +
  geom_histogram(position = "dodge", bins = 10) +
  labs(title = "Multinomial Distribution", x = "Value", y = "Frequency") +
  theme_minimal() +
  scale_fill_viridis_d()

"""Summary Tables by categories:

Cab Type
"""

cab_type_summary <- cleaned_data %>%
  group_by(cab_type) %>%
  summarise(
    avg_price = mean(price, na.rm = TRUE),
    avg_surge = mean(surge_multiplier, na.rm = TRUE)
  )

print(cab_type_summary)

"""Time of the day"""

time_of_day_summary <- cleaned_data %>%
  group_by(hour(datetime)) %>%
  summarise(
    avg_price = mean(price, na.rm = TRUE),
    avg_surge = mean(surge_multiplier, na.rm = TRUE)
  )

print(time_of_day_summary)

"""Heat Map (lat-long-distance)

"""

library(ggplot2)
library(dplyr)
library(viridis)



heatmap_data <- cleaned_data %>%
  select_if(is.numeric) %>%
  na.omit()


cor_matrix <- cor(heatmap_data, use = "complete.obs")

cor_data <- as.data.frame(as.table(cor_matrix))
colnames(cor_data) <- c("Variable1", "Variable2", "Correlation")

ggplot(cor_data, aes(x = Variable1, y = Variable2, fill = Correlation)) +
  geom_tile(color = "white", lwd = 0.5) +
  scale_fill_viridis(option = "C", name = "Correlation", direction = -1) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, size = 10, color = "darkblue"),
    axis.text.y = element_text(size = 10, color = "darkblue"),
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5)
  ) +
  labs(title = "Enhanced Correlation Heatmap for Numerical Variables",
       x = "Variables",
       y = "Variables")

"""Decision Tree intial draft"""

install.packages("rpart")
install.packages("rpart.plot")
library(rpart)
library(rpart.plot)


set.seed(42)
n_samples <- 1000
hour <- sample(0:23, n_samples, replace = TRUE)
day <- sample(1:30, n_samples, replace = TRUE)
month <- sample(1:12, n_samples, replace = TRUE)
price <- runif(n_samples, 10, 100)

# Categorical Variables
source <- sample(c("A", "B", "C"), n_samples, replace = TRUE)
destination <- sample(c("X", "Y", "Z"), n_samples, replace = TRUE)
cab_type <- sample(c("Uber", "Lyft"), n_samples, replace = TRUE)

# Combine into a dataframe
data <- data.frame(hour, day, month, price, source, destination, cab_type)

# Combine date and time to create a datetime column
data$datetime <- as.POSIXct(paste(2025, data$month, data$day, data$hour, sep = "-"), format = "%Y-%m-%d-%H")

# Sort by datetime
data <- data[order(data$datetime), ]

# Decision Tree
# Convert 'cab_type' to a factor
data$cab_type <- as.factor(data$cab_type)

# Create the decision tree model
decision_tree <- rpart(cab_type ~ hour + day + month + price, data = data, method = "class")

# Plot the decision tree
rpart.plot(decision_tree, main = "Decision Tree for Cab Type Prediction")

if (!require(caret)) install.packages("caret")
if (!require(rpart)) install.packages("rpart")
if (!require(rpart.plot)) install.packages("rpart.plot")
if (!require(pROC)) install.packages("pROC")

library(caret)
library(rpart)
library(rpart.plot)
library(pROC)


set.seed(42)
n_samples <- 1000
hour <- sample(0:23, n_samples, replace = TRUE)
day <- sample(1:30, n_samples, replace = TRUE)
month <- sample(1:12, n_samples, replace = TRUE)
price <- runif(n_samples, 10, 100)

# Categorical Variables
source <- sample(c("A", "B", "C"), n_samples, replace = TRUE)
destination <- sample(c("X", "Y", "Z"), n_samples, replace = TRUE)
surge_multiplier <- sample(c(1, 1.5, 2), n_samples, replace = TRUE)

data <- data.frame(hour, day, month, price, source, destination, surge_multiplier)

data$surge_multiplier <- as.factor(data$surge_multiplier)

# datetime column
data$datetime <- as.POSIXct(paste(2025, data$month, data$day, data$hour, sep = "-"), format = "%Y-%m-%d-%H")

# Data Check
cat("Total rows in data:", nrow(data), "\n")

# Data Splitting (70-30 Split)
set.seed(42)
train_index <- createDataPartition(data$surge_multiplier, p = 0.7, list = FALSE)
train_data <- data[train_index, ]
test_data <- data[-train_index, ]

cat("Number of rows in train_data:", nrow(train_data), "\n")
cat("Number of rows in test_data:", nrow(test_data), "\n")

# Train Decision Tree Model
decision_tree <- rpart(surge_multiplier ~ hour + day + month + price, data = train_data, method = "class")
rpart.plot(decision_tree, main = "Decision Tree for Surge Multiplier Prediction")

# Predict on Test Data
predictions <- predict(decision_tree, test_data, type = "class")

# Check for Missing Predictions
cat("Number of missing predictions:", sum(is.na(predictions)), "\n")
cat("Length of predictions:", length(predictions), "\n")
cat("Length of test_data surge_multiplier:", length(test_data$surge_multiplier), "\n")

# Confusion Matrix
conf_matrix <- confusionMatrix(predictions, test_data$surge_multiplier)
print(conf_matrix)

# Verify Total Count in Confusion Matrix
conf_matrix_sum <- sum(conf_matrix$table)
cat("Total count in confusion matrix:", conf_matrix_sum, "\n")

# Extract Metrics
accuracy <- conf_matrix$overall['Accuracy']
precision <- conf_matrix$byClass['Pos Pred Value']
recall <- conf_matrix$byClass['Sensitivity']
f1_score <- 2 * (precision * recall) / (precision + recall)

# Display Metrics
cat("\nModel Evaluation Metrics for Surge Multiplier:\n")
cat("Accuracy: ", accuracy, "\n")
cat("Precision: ", precision, "\n")
cat("Recall: ", recall, "\n")
cat("F1 Score: ", f1_score, "\n")

# ROC and AUC Calculation
pred_prob <- predict(decision_tree, test_data, type = "prob")

# Since 'surge_multiplier' has multiple classes, we need to calculate ROC and AUC for each class
roc_curves <- lapply(levels(test_data$surge_multiplier), function(level) {
  roc(test_data$surge_multiplier == level, pred_prob[, level])
})

# Plot ROC Curves
plot(roc_curves[[1]], col = "red", main = "ROC Curves for Surge Multiplier Prediction")
for (i in 2:length(roc_curves)) {
  plot(roc_curves[[i]], col = i + 1, add = TRUE)
}
legend("bottomright", legend = levels(test_data$surge_multiplier), col = 2:(length(roc_curves) + 1), lwd = 2)

# Calculate AUC for each class
auc_values <- sapply(roc_curves, auc)
print(auc_values)

"""STATISTICAL TESTS & CI

T-test
"""

install.packages("nortest")
install.packages("e1071")

library(nortest)
library(e1071)

#non numerical
clean_data <- function(data) {

  data <- data[complete.cases(data), ]

  data <- data[, sapply(data, is.numeric)]

  return(data)
}


perform_normality_tests <- function(cleaned_data) {

  data <- clean_data(cleaned_data)

  normally_distributed <- list()
  not_normally_distributed <- list()


  for (feature in names(data)) {
    cat("Normality Tests for Feature:", feature, "\n")

    # Kolmogorov-Smirnov test
    ks_test <- try(ks.test(data[[feature]], "pnorm", mean(data[[feature]]), sd(data[[feature]])), silent = TRUE)
    if (inherits(ks_test, "try-error")) {
      cat("Error in Kolmogorov-Smirnov Test\n")
      next
    }

    # Anderson-Darling test
    ad_test <- try(ad.test(data[[feature]]), silent = TRUE)
    if (inherits(ad_test, "try-error")) {
      cat("Error in Anderson-Darling Test\n")
      next
    }

    # Skewness and Kurtosis
    skew <- skewness(data[[feature]], na.rm = TRUE)
    kurt <- kurtosis(data[[feature]], na.rm = TRUE)

    #results
    cat("Kolmogorov-Smirnov Test p-value:", ks_test$p.value, "\n")
    cat("Anderson-Darling Test p-value:", ad_test$p.value, "\n")
    cat("Skewness:", skew, "\n")
    cat("Kurtosis:", kurt, "\n")

    # Decision
    if (ks_test$p.value > 0.05 && ad_test$p.value > 0.05) {
      cat("Conclusion: The feature appears to be normally distributed.\n")
      normally_distributed[[feature]] <- TRUE
    } else {
      cat("Conclusion: The feature does not appear to be normally distributed.\n")
      not_normally_distributed[[feature]] <- TRUE
    }

    cat("\n")
  }


  list(
    normally_distributed = names(normally_distributed),
    not_normally_distributed = names(not_normally_distributed)
  )
}


result <- perform_normality_tests(cleaned_data)


cat("Normally Distributed Features:\n")
print(result$normally_distributed)

cat("\nNot Normally Distributed Features:\n")
print(result$not_normally_distributed)

# subset the data => Lyft and Uber
lyft_data <- cleaned_data[data$cab_type == "Lyft", ]
uber_data <- cleaned_data[data$cab_type == "Uber", ]

# check if the length is the same for paired comparison
if (nrow(lyft_data) == nrow(uber_data)) {

  wilcox_price <- wilcox.test(lyft_data$price, uber_data$price, paired = TRUE)

  wilcox_distance <- wilcox.test(lyft_data$distance, uber_data$distance, paired = TRUE)

  wilcox_surge <- wilcox.test(lyft_data$surge_multiplier, uber_data$surge_multiplier, paired = TRUE)

  cat("Wilcoxon Test for Price\n")
  print(wilcox_price)

  cat("\nWilcoxon Test for Distance\n")
  print(wilcox_distance)

  cat("\nWilcoxon Test for Surge Multiplier\n")
  print(wilcox_surge)

} else {
  cat("The data for Lyft and Uber is not paired. You cannot perform the Wilcoxon Signed-Rank Test without paired data.")
}

# paired numeric features
wilcoxon_pairs <- list(
  c("temperature", "apparentTemperature"),
  c("temperatureHigh", "apparentTemperatureHigh"),
  c("temperatureLow", "apparentTemperatureLow"),
  c("temperatureMin", "apparentTemperatureMin"),
  c("temperatureMax", "apparentTemperatureMax")
)

for (pair in wilcoxon_pairs) {
  var1 <- pair[1]
  var2 <- pair[2]

  df <- na.omit(cleaned_data[, c(var1, var2)])


  test_result <- wilcox.test(df[[var1]], df[[var2]], paired = TRUE)


  cat("\nWilcoxon Signed-Rank Test:", var1, "vs", var2, "\n")
  cat("W =", round(test_result$statistic, 2), " | p-value =", round(test_result$p.value, 4), "\n")

  if (test_result$p.value < 0.05) {
    cat("Conclusion: The medians of", var1, "and", var2, "are significantly different.\n")
  } else {
    cat("Conclusion: No significant difference in medians between", var1, "and", var2, ".\n")
  }
}

#  Spearman correlation test
spearman_pairs <- list(
  c("temperature", "apparentTemperature"),
  c("precipIntensity", "precipProbability"),
  c("windSpeed", "windGust"),
  c("windSpeed", "windBearing"),
  c("temperatureHigh", "apparentTemperatureHigh"),
  c("temperatureLow", "apparentTemperatureLow"),
  c("precipIntensity", "precipIntensityMax"),
  c("temperatureMin", "apparentTemperatureMin"),
  c("temperatureMax", "apparentTemperatureMax"),
  c("price", "latitude"),
  c("price", "longitude")
)


for (pair in spearman_pairs) {
  var1 <- pair[1]
  var2 <- pair[2]


  df <- na.omit(cleaned_data[, c(var1, var2)])


  test_result <- cor.test(df[[var1]], df[[var2]], method = "spearman")


  cat("\nSpearman Correlation Test:", var1, "vs", var2, "\n")
  cat("rho =", round(test_result$estimate, 4), " | p-value =", round(test_result$p.value, 4), "\n")

  if (test_result$p.value < 0.05) {
    cat("Conclusion: Significant correlation.\n")
  } else {
    cat("Conclusion: No significant correlation.\n")
  }
}

"""Chi-Square"""

if (!require(gtools)) install.packages("gtools", dependencies = TRUE)
library(gtools)

# ensure variables are factors
categorical_vars <- c("source", "destination", "cab_type", "name",
                      "short_summary", "long_summary", "icon")

cleaned_data[categorical_vars] <- lapply(cleaned_data[categorical_vars], as.factor)

# all unique combinations
pairs <- combinations(n = length(categorical_vars), r = 2, v = categorical_vars)

# Chi-Square tests fun
perform_chi_square_tests <- function(cleaned_data, pairs) {
  significant <- list()
  independent <- list()
  results <- list()

  for (i in 1:nrow(pairs)) {
    var1 <- pairs[i, 1]
    var2 <- pairs[i, 2]

    tbl <- table(cleaned_data[[var1]], data[[var2]])


    if (any(tbl == 0)) next

    test <- chisq.test(tbl)


    results[[paste(var1, "vs", var2)]] <- list(
      chi2 = round(test$statistic, 2),
      p_value = round(test$p.value, 4),
      table = tbl
    )

    cat("\nChi-Square Test:", var1, "vs", var2, "\n")
    print(tbl)
    cat("Chi-square =", round(test$statistic, 2), " | p-value =", round(test$p.value, 4), "\n")

    if (test$p.value < 0.05) {
      cat("Conclusion: Variables are likely DEPENDENT.\n")
      significant[[paste(var1, "vs", var2)]] <- TRUE
    } else {
      cat("Conclusion: Variables are likely INDEPENDENT.\n")
      independent[[paste(var1, "vs", var2)]] <- TRUE
    }
  }

  return(list(
    all_results = results,
    significant_pairs = names(significant),
    independent_pairs = names(independent)
  ))
}


chi_summary <- perform_chi_square_tests(data, pairs)

cat("\n\nSignificant (Dependent) Variable Pairs\n")
for (i in 1:length(chi_summary$significant_pairs)) {
  cat(i, ". ", chi_summary$significant_pairs[i], "\n")
}

cat("\n\nIndependent Variable Pairs\n")
for (i in 1:length(chi_summary$independent_pairs)) {
  cat(i, ". ", chi_summary$independent_pairs[i], "\n")
}

categorical_vars <- c("source", "destination", "cab_type", "name",
                      "short_summary", "long_summary", "icon")

pairs <- combn(categorical_vars, 2, simplify = FALSE)

results <- data.frame(
  Variable1 = character(),
  Variable2 = character(),
  Chi_Square = numeric(),
  p_value = numeric(),
  Conclusion = character(),
  stringsAsFactors = FALSE
)

for (pair in pairs) {
  var1 <- pair[1]
  var2 <- pair[2]


  tbl <- table(cleaned_data[[var1]], cleaned_data[[var2]])


  if (any(dim(tbl) < 2)) next


  test <- chisq.test(tbl)


  conclusion <- if (test$p.value < 0.05) {
    "Dependent (Reject H0)"
  } else {
    "Independent (Fail to Reject H0)"
  }


  results <- rbind(results, data.frame(
    Variable1 = var1,
    Variable2 = var2,
    Chi_Square = round(test$statistic, 2),
    p_value = round(test$p.value, 4),
    Conclusion = conclusion,
    stringsAsFactors = FALSE
  ))
}


results <- results[order(results$p_value), ]
rownames(results) <- NULL
print(results)

pairs <- list(
  c("temperature", "apparentTemperature"),
  c("precipIntensity", "precipProbability"),
  c("windSpeed", "windGust"),
  c("windSpeed", "windBearing"),
  c("temperatureHigh", "apparentTemperatureHigh"),
  c("temperatureLow", "apparentTemperatureLow"),
  c("precipIntensity", "precipIntensityMax"),
  c("temperatureMin", "apparentTemperatureMin"),
  c("temperatureMax", "apparentTemperatureMax")
)


for (pair in pairs) {
  var1 <- pair[1]
  var2 <- pair[2]

  cat("\n==============================\n")
  cat("Comparison:", var1, "vs", var2, "\n")

  x <- cleaned_data[[var1]]
  y <- cleaned_data[[var2]]

  mean_test <- t.test(x, y, paired = TRUE)
  cat("\nPaired t-test (Difference in Means):\n")
  cat("t =", round(mean_test$statistic, 4),
      "| p-value =", signif(mean_test$p.value, 4), "\n")

  # F-test for variances
  var_test <- var.test(x, y)
  cat("F-test (Ratio of Variances):\n")
  cat("F =", round(var_test$statistic, 4),
      "| p-value =", signif(var_test$p.value, 4), "\n")

  cat("\n--- Interpretation ---\n")
  if (mean_test$p.value < 0.05) {
    cat("Means: Significant difference → Variables behave differently.\n")
  } else {
    cat("Means: No significant difference → Potential redundancy; consider removing one.\n")
  }

  if (var_test$p.value < 0.05) {
    cat("Variances: Significant difference → One may be more variable; assess based on domain or model needs.\n")
  } else {
    cat("Variances: No significant difference → Spread is similar; may reinforce redundancy.\n")
  }
}

categorical_vars <- c("source", "destination", "cab_type", "name",
                      "short_summary", "long_summary", "icon")


pairs <- combn(categorical_vars, 2, simplify = FALSE)

results <- tibble::tibble(
  Variable1 = character(),
  Variable2 = character(),
  Chi_Square = numeric(),
  p_value = numeric(),
  Conclusion = character(),
  Fisher_statistic = numeric(),
  stringsAsFactors = FALSE
)


compute_fisher_statistic <- function(p_values) {

  chi_squared_stat <- -2 * sum(log(p_values))
  return(chi_squared_stat)
}


for (pair in pairs) {
  var1 <- pair[1]
  var2 <- pair[2]


  tbl <- table(cleaned_data[[var1]], cleaned_data[[var2]])


  if (any(dim(tbl) < 2)) next


  test <- tryCatch({
    chisq.test(tbl)
  }, warning = function(w) {
    if (grepl("Chi-squared approximation may be incorrect", w$message)) {
      return(fisher.test(tbl))
    }
  }, error = function(e) {
    return(NULL)
  })

  if (is.null(test)) next


  fisher_stat <- NA

  if (inherits(test, "htest") && "p.value" %in% names(test) && inherits(test, "fisher.test")) {

    fisher_stat <- compute_fisher_statistic(c(test$p.value))  # You can extend this for more tests if needed
  }

  conclusion <- if (test$p.value < 0.05) {
    "Dependent (Reject H0)"
  } else {
    "Independent (Fail to Reject H0)"
  }


  results <- rbind(results, tibble::tibble(
    Variable1 = var1,
    Variable2 = var2,
    Chi_Square = ifelse(is.null(test$statistic), NA, round(test$statistic, 2)),
    p_value = round(test$p.value, 4),
    Conclusion = conclusion,
    Fisher_statistic = round(fisher_stat, 2)
  ))
}


print(results, n = Inf)

results <- tibble::tibble(
  Variable1 = character(),
  Variable2 = character(),
  Chi_Square = numeric(),
  p_value = numeric(),
  Adjusted_p_value = numeric(),
  Conclusion = character(),
  Fisher_statistic = numeric(),
  stringsAsFactors = FALSE
)

num_tests <- length(pairs)

alpha_adjusted <- 0.05 / num_tests

for (pair in pairs) {
  var1 <- pair[1]
  var2 <- pair[2]

  tbl <- table(cleaned_data[[var1]], cleaned_data[[var2]])

  if (any(dim(tbl) < 2)) next


  test <- tryCatch({
    chisq.test(tbl)
  }, warning = function(w) {
    if (grepl("Chi-squared approximation may be incorrect", w$message)) {
      return(fisher.test(tbl))
    }
  }, error = function(e) {
    return(NULL)
  })

  if (is.null(test)) next


  adjusted_p_value <- test$p.value * num_tests


  adjusted_p_value <- min(adjusted_p_value, 1)


  conclusion <- if (adjusted_p_value < 0.05) {
    "Dependent (Reject H0)"
  } else {
    "Independent (Fail to Reject H0)"
  }


  fisher_stat <- 0


  if (inherits(test, "htest") && "p.value" %in% names(test) && test$p.value == 1) {

    fisher_stat <- compute_fisher_statistic(c(test$p.value))
  }


  results <- rbind(results, tibble::tibble(
    Variable1 = var1,
    Variable2 = var2,
    Chi_Square = ifelse(is.null(test$statistic), NA, round(test$statistic, 2)),
    p_value = round(test$p.value, 4),
    Adjusted_p_value = round(adjusted_p_value, 4),
    Conclusion = conclusion,
    Fisher_statistic = round(fisher_stat, 2)
  ))
}

print(results, n = Inf)

results <- tibble::tibble(
  Variable1 = character(),
  Variable2 = character(),
  Chi_Square = numeric(),
  p_value = numeric(),
  Adjusted_p_value = numeric(),
  Conclusion = character(),
  Fisher_statistic = numeric(),
  Conclusion_Change = character(),
  stringsAsFactors = FALSE
)


num_tests <- length(pairs)


previous_conclusion <- NULL


for (pair in pairs) {
  var1 <- pair[1]
  var2 <- pair[2]


  tbl <- table(cleaned_data[[var1]], cleaned_data[[var2]])

  if (any(dim(tbl) < 2)) next

  test <- tryCatch({
    chisq.test(tbl)
  }, warning = function(w) {
    if (grepl("Chi-squared approximation may be incorrect", w$message)) {
      return(fisher.test(tbl))
    }
  }, error = function(e) {
    return(NULL)
  })

  if (is.null(test)) next


  p_value <- test$p.value
  adjusted_p_value <- p_value

  conclusion <- if (p_value < 0.05) {
    "Dependent (Reject H0)"
  } else {
    "Independent (Fail to Reject H0)"
  }

  fisher_stat <- 0

  if (inherits(test, "htest") && "p.value" %in% names(test) && test$p.value == 1) {

    fisher_stat <- compute_fisher_statistic(c(test$p.value))
  }

  # compare conclusion with the previous conclusion to track changes
  adjusted_conclusion <- if (adjusted_p_value < 0.05) {
    "Dependent (Reject H0)"
  } else {
    "Independent (Fail to Reject H0)"
  }


  conclusion_change <- ifelse(conclusion == adjusted_conclusion, "No Change", "Changed")


  previous_conclusion <- adjusted_conclusion


  results <- rbind(results, tibble::tibble(
    Variable1 = var1,
    Variable2 = var2,
    Chi_Square = ifelse(is.null(test$statistic), NA, round(test$statistic, 2)),
    p_value = round(p_value, 4),
    Adjusted_p_value = round(adjusted_p_value, 4),  # Use the same p-value for adjusted
    Conclusion = adjusted_conclusion,
    Fisher_statistic = round(fisher_stat, 2),
    Conclusion_Change = conclusion_change
  ))
}

# Display results without truncation
print(results, n = Inf)
View(results)

"""Make sure cv% for allvalues is included in summary stats"""

# Summary and Description with CV%

# function to compute all required statistics
get_stats <- function(x) {
  if (is.numeric(x)) {
    m <- mean(x, na.rm = TRUE)
    s <- sd(x, na.rm = TRUE)
    tibble::tibble(
      Mean = m,
      Median_Q2 = median(x, na.rm = TRUE),
      Mode = as.character(names(sort(table(x), decreasing = TRUE)[1])),
      SD = s,
      CV_percent = ifelse(m != 0, (s / m) * 100, NA),
      Min = min(x, na.rm = TRUE),
      Q1 = quantile(x, 0.25, na.rm = TRUE),
      Q3 = quantile(x, 0.75, na.rm = TRUE),
      Max = max(x, na.rm = TRUE)
    )
  } else {
    tibble::tibble(
      Mean = NA, Median_Q2 = NA, Mode = NA,
      SD = NA, CV_percent = NA,
      Min = NA, Q1 = NA, Q3 = NA, Max = NA
    )
  }
}

summary_df <- purrr::map_dfr(data, get_stats, .id = "Variable")


print(summary_df)

"""ANOVA TEST"""

# ------------ TWO-WAY ANOVA TABLES FOR DIFFERENT FACTORS ----------------

equal_samples_df$source <- as.factor(equal_samples_df$source)
equal_samples_df$destination <- as.factor(equal_samples_df$destination)
equal_samples_df$hour <- as.factor(equal_samples_df$hour)
equal_samples_df$long_summary <- as.factor(equal_samples_df$long_summary)
equal_samples_df$cab_type <- as.factor(equal_samples_df$cab_type)
equal_samples_df$short_summary <- as.factor(equal_samples_df$short_summary)
equal_samples_df$month <- as.factor(equal_samples_df$month)

# Using price, and Factor A: source, Factor B: destination
anova_result_two_way <- aov(price ~ source * destination, data = equal_samples_df)
summary(anova_result_two_way)

# Using distance, and Factor A: source , Factor B: destination
anova_result_two_way <- aov(distance ~ source * destination, data = equal_samples_df)
summary(anova_result_two_way)

# Using temperature, and Factor A: source , Factor B: hour
anova_result_two_way <- aov(temperature ~ source * hour, data = equal_samples_df)
summary(anova_result_two_way)

# Using apparentTemperature, and Factor A: source , Factor B: hour
anova_result_two_way <- aov(apparentTemperature ~ source * hour, data = equal_samples_df)
summary(anova_result_two_way)

# Using visibility, and Factor A: destination , Factor B: long_summary
anova_result_two_way <- aov(visibility ~ destination * long_summary, data = equal_samples_df)
summary(anova_result_two_way)

# Using distance, and Factor A: source , Factor B: cab_type
anova_result_two_way <- aov(distance ~ source * cab_type, data = equal_samples_df)
summary(anova_result_two_way)

# Using temperature, and Factor A: short_summary , Factor B: hour
anova_result_two_way <- aov(temperature ~ short_summary * hour, data = equal_samples_df)
summary(anova_result_two_way)

# Using windSpeed, and Factor A: month , Factor B: short_summary
anova_result_two_way <- aov(windSpeed ~ month * short_summary, data = equal_samples_df)
summary(anova_result_two_way)

# Using visibility, and Factor A: source , Factor B: long_summary
anova_result_two_way <- aov(visibility ~ source * long_summary, data = equal_samples_df)
summary(anova_result_two_way)

# Using distance, and Factor A: hour , Factor B: destination
anova_result_two_way <- aov(distance ~ hour * destination, data = equal_samples_df)
summary(anova_result_two_way)

# Using ozone, and Factor A: month , Factor B: short_summary
anova_result_two_way <- aov(ozone ~ month * short_summary, data = equal_samples_df)
summary(anova_result_two_way)

# DISCARDED TWO-WAY ANOVA TABLES
equal_samples_df$hour <- as.factor(equal_samples_df$hour)
equal_samples_df$day <- as.factor(equal_samples_df$day)
equal_samples_df$month <- as.factor(equal_samples_df$month)
equal_samples_df$cab_type <- as.factor(equal_samples_df$cab_type)
equal_samples_df$short_summary <- as.factor(equal_samples_df$short_summary)
equal_samples_df$name <- as.factor(equal_samples_df$name)
equal_samples_df$icon <- as.factor(equal_samples_df$icon)

# USING price, AND FACT A: hour , FACT B: day
anova_result_two_way <- aov(price ~ hour * day, data = equal_samples_df)
summary(anova_result_two_way)

# USING price, AND FACT A: month , FACT B: cab_type
anova_result_two_way <- aov(price ~ month * cab_type, data = equal_samples_df)
summary(anova_result_two_way)

# USING distance, AND FACT A: short_summary , FACT B: cab_type
anova_result_two_way <- aov(distance ~ short_summary * cab_type, data = equal_samples_df)
summary(anova_result_two_way)

# USING distance, AND FACT A: hour , FACT B: name
anova_result_two_way <- aov(distance ~ hour * name, data = equal_samples_df)
summary(anova_result_two_way)

# USING surge_multiplier, AND FACT A: name , FACT B: icon
anova_result_two_way <- aov(surge_multiplier ~ name * icon, data = equal_samples_df)
summary(anova_result_two_way)

"""## MODELS

### CLASSIFICATION MODELS

**Naive Bayes Classification**
"""

# ******************** NAIVE BAYES CLASSIFICATION *************************

# Pre-processing

# Copy the original data to avoid overwriting
nb_data <- equal_samples_df

# Remove NA's (Naive Bayes can't handle them)
nb_data <- na.omit(nb_data)

# Convert categorical variables to factors
nb_data$cab_type <- as.factor(nb_data$cab_type)
nb_data$hour <- as.factor(nb_data$hour)
nb_data$source <- as.factor(nb_data$source)
nb_data$short_summary <- as.factor(nb_data$short_summary)
nb_data$name <- as.factor(nb_data$name)

"""Unbinned & Binned NB Classifications"""

# ---------------- UNBINNED NAIVE-BAYES CLASSIFICATION ----------------

# =========== UNBINNED MODEL 1 ==========
# Prepare model
model_NB_1 <- naiveBayes(cab_type ~ hour + source + distance + surge_multiplier + short_summary, data = nb_data)
print(model_NB_1)
# Predict on training data
prediction_NB_1 <- predict(model_NB_1, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_1, Actual = nb_data$cab_type)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 1 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== UNBINNED MODEL 2 ==========
# Prepare model
model_NB_2 <- naiveBayes(name ~ cab_type + hour + price + distance + short_summary, data = nb_data)
print(model_NB_2)
# Predict on training data
prediction_NB_2 <- predict(model_NB_2, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_2, Actual = nb_data$name)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 2 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== UNBINNED MODEL 3 ==========
# Prepare model
model_NB_3 <- naiveBayes(source ~ hour + cab_type + surge_multiplier + temperature + windBearing, data = nb_data)
print(model_NB_3)
# Predict on training data
prediction_NB_3 <- predict(model_NB_3, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_3, Actual = nb_data$source)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 3 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== UNBINNED MODEL 4 ==========
# Prepare model
model_NB_4 <- naiveBayes(short_summary ~ temperature + windBearing + hour, data = nb_data)
print(model_NB_4)
# Predict on training data
prediction_NB_4 <- predict(model_NB_4, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_4, Actual = nb_data$short_summary)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 4 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2), "%\n")


# ------------------ BINNED NAIVE-BAYES CLASSIFICATION --------------------

# Bin continuous variables into categories
nb_data$distance_bin <- cut(nb_data$distance, breaks = 5, labels = FALSE)
nb_data$surge_bin <- cut(nb_data$surge_multiplier, breaks = c(0, 1, 1.5, 2, Inf), labels = c("normal", "low", "med", "high"))
nb_data$price_bin <- cut(nb_data$price, breaks = 5, labels = FALSE)
nb_data$temp_bin <- cut(nb_data$temperature, breaks = 5, labels = FALSE)

# Convert to factor
nb_data$distance_bin <- as.factor(nb_data$distance_bin)
nb_data$surge_bin <- as.factor(nb_data$surge_bin)
nb_data$price_bin <- as.factor(nb_data$price_bin)
nb_data$temp_bin <- as.factor(nb_data$temp_bin)

# =========== BINNED MODEL 1 ===========
# Prepare model
model_NB_1 <- naiveBayes(cab_type ~ hour + source + distance_bin + surge_bin + short_summary, data = nb_data)
print(model_NB_1)
# Predict on training data
prediction_NB_1 <- predict(model_NB_1, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_1, Actual = nb_data$cab_type)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 1 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== BINNED MODEL 2 ===========
# Prepare model
model_NB_2 <- naiveBayes(name ~ cab_type + hour + price_bin + distance_bin + short_summary, data = nb_data)
print(model_NB_2)
# Predict on training data
prediction_NB_2 <- predict(model_NB_2, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_2, Actual = nb_data$name)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 2 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== BINNED MODEL 3 ===========
# Prepare model
model_NB_3 <- naiveBayes(source ~ hour + cab_type + surge_bin + temp_bin + windBearing, data = nb_data)
print(model_NB_3)
# Predict on training data
prediction_NB_3 <- predict(model_NB_3, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_3, Actual = nb_data$source)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 3 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")


# =========== BINNED MODEL 4 ===========
# Prepare model
model_NB_4 <- naiveBayes(short_summary ~ temp_bin + windBearing + hour, data = nb_data)
print(model_NB_4)
# Predict on training data
prediction_NB_4 <- predict(model_NB_4, nb_data)
# Confusion matrix
conf_matrix <- table(Predicted = prediction_NB_4, Actual = nb_data$short_summary)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model 4 Accuracy:", accuracy, " --> ", round(accuracy * 100, 2), "%\n")

"""k-Fold Cross-Validation for Unbinned and Binned"""

# ****************** k-Fold Cross-Validation (5 folds) ******************

ctrl <- trainControl(method = "cv", number = 5)
tuneGrid = expand.grid(laplace = 0, usekernel = FALSE, adjust = 1)

# ------------- UNBINNED CV MODELS -----------------

# =========== MODEL 1: Predict cab_type ===========
cv_unbinned_1 <- train(cab_type ~ hour + source + distance + surge_multiplier + short_summary, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Unbinned Model 1 Accuracy:", max(cv_unbinned_1$results$Accuracy) * 100, "%\n")

# =========== MODEL 2: Predict name ===========
cv_unbinned_2 <- train(name ~ cab_type + hour + price + distance + short_summary, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Unbinned Model 2 Accuracy:", max(cv_unbinned_2$results$Accuracy) * 100, "%\n")

# =========== MODEL 3: Predict source ===========
cv_unbinned_3 <- train(source ~ hour + cab_type + surge_multiplier + temperature + windBearing, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Unbinned Model 3 Accuracy:", max(cv_unbinned_3$results$Accuracy) * 100, "%\n")

# =========== MODEL 4: Predict short_summary ===========
cv_unbinned_4 <- train(short_summary ~ temperature + windBearing + hour, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Unbinned Model 4 Accuracy:", max(cv_unbinned_4$results$Accuracy) * 100, "%\n")


# --------------- BINNED CV MODELS -------------------

# =========== MODEL 1: Predict cab_type (binned) ===========
cv_binned_1 <- train(cab_type ~ hour + source + distance_bin + surge_bin + short_summary, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Binned Model 1 Accuracy:", max(cv_binned_1$results$Accuracy) * 100, "%\n")

# =========== MODEL 2: Predict name (binned) ===========
cv_binned_2 <- train(name ~ cab_type + hour + price_bin + distance_bin + short_summary, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Binned Model 2 Accuracy:", max(cv_binned_2$results$Accuracy) * 100, "%\n")

# =========== MODEL 3: Predict source (binned) ===========
cv_binned_3 <- train(source ~ hour + cab_type + surge_bin + windBearing, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Binned Model 3 Accuracy:", max(cv_binned_3$results$Accuracy) * 100, "%\n")

# =========== MODEL 4: Predict short_summary (binned) ===========
cv_binned_4 <- train(short_summary ~ temp_bin + windBearing + hour, data = nb_data, method = "naive_bayes", trControl = ctrl, tuneGrid = tuneGrid)
cat("CV Binned Model 4 Accuracy:", max(cv_binned_4$results$Accuracy) * 100, "%\n")

"""For surge multiplier classification"""

# Create the new classified dataset with 'surge' column
classified <- cleaned_data
classified$surge <- ifelse(classified$surge_multiplier > 1, "yes", "no")
classified$surge <- as.factor(classified$surge)

# Check result
table(classified$surge)

"""**Logistic Regression**"""

# ************************ LOGISTICAL REGRESSION ****************************

# Convert necessary variables to factors
cleaned_data$cab_type <- as.factor(cleaned_data$cab_type)
cleaned_data$hour <- as.factor(cleaned_data$hour)
cleaned_data$day <- as.factor(cleaned_data$day)

# Handle missing values (you can also choose to impute)
cleaned_data <- na.omit(cleaned_data)

"""Cab Type"""

# ----------------- Model 1: Predicting Cab Type (cab_type) ----------------

# Logistic regression model to predict cab_type
cabtype_model <- glm(cab_type ~ hour + day + distance + price + temperature + humidity, data = cleaned_data, family = binomial)

# View results
summary(cabtype_model)

# Odds ratios for cabtype_model
cat("\nOdds Ratios for Cab Type Model:\n")
odds_ratios_cabtype <- exp(coef(cabtype_model))
print(odds_ratios_cabtype)

# Odd ratios for 95% Confidence Intervals
cat("\nOdds Ratio CI for Cab Type (95%):\n")
odds_ratios_cabtype_CI <- exp(confint.default(cabtype_model))
print(odds_ratios_cabtype_CI)

# VIF for cab_type model
vif(cabtype_model)

# Predicting on training data (for demo; use test data in real analysis)
cabtype_pred <- predict(cabtype_model, type = "response") > 0.5

# Actual vs Predicted
conf_matrix <- table(Predicted = cabtype_pred, Actual = cleaned_data$cab_type)
print(conf_matrix)
# Evaluate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")

"""Surge Multiplier"""

cleaned_data$is_surge <- ifelse(cleaned_data$surge_multiplier > 1, 1, 0)
cleaned_data$is_surge <- as.factor(cleaned_data$is_surge)


surge_model <- glm(is_surge ~ cab_type + hour + day + distance + temperature + humidity + windSpeed, data = cleaned_data, family = binomial)

summary(surge_model)

cat("\nOdds Ratios for Surge Model:\n")
odds_ratios_surge <- exp(coef(surge_model))
print(odds_ratios_surge)


cat("\nOdds Ratio CI for Surge (95%):\n")
odds_ratios_surge_CI <- exp(confint.default(surge_model))
print(odds_ratios_surge_CI)

vif(surge_model)


surge_pred <- predict(surge_model, type = "response") > 0.5

conf_matrix <- table(Predicted = surge_pred, Actual = cleaned_data$is_surge)
print(conf_matrix)

accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Model Accuracy:", accuracy, " --> ", round(accuracy * 100, 2),"%\n")

"""DTC"""

install.packages("rpart")
install.packages("rpart.plot")
library(rpart)
library(rpart.plot)


set.seed(42)
n_samples <- 250
hour <- sample(0:23, n_samples, replace = TRUE)
day <- sample(1:30, n_samples, replace = TRUE)
month <- sample(1:12, n_samples, replace = TRUE)
price <- runif(n_samples, 10, 100)

source <- sample(c("A", "B", "C"), n_samples, replace = TRUE)
destination <- sample(c("X", "Y", "Z"), n_samples, replace = TRUE)
cab_type <- sample(c("Uber", "Lyft"), n_samples, replace = TRUE)

data <- data.frame(hour, day, month, price, source, destination, cab_type)

data$datetime <- as.POSIXct(paste(2025, data$month, data$day, data$hour, sep = "-"), format = "%Y-%m-%d-%H")

data <- data[order(data$datetime), ]

data$cab_type <- as.factor(data$cab_type)

decision_tree <- rpart(cab_type ~ hour + day + month + price, data = data, method = "class")

rpart.plot(decision_tree, main = "Decision Tree for Cab Type Prediction")

#Metric Analysis for the Decision Tree

if (!require(caret)) install.packages("caret")
if (!require(rpart)) install.packages("rpart")
if (!require(rpart.plot)) install.packages("rpart.plot")
if (!require(pROC)) install.packages("pROC")
if (!require(dplyr)) install.packages("dplyr")
library(caret)
library(rpart)
library(rpart.plot)
library(pROC)
library(dplyr)
data <- read.csv("rideshare_kaggle.csv", header = TRUE)
glimpse(data)
target_features <- c('hour', 'day', 'month', 'price', 'distance',
'latitude', 'longitude', 'temperature', 'apparentTemperature')
target_features <- target_features[target_features %in% names(data)]
data <- data %>%
 select(all_of(target_features), surge_multiplier) %>%
 na.omit()
str(data)
data$surge_multiplier <- as.factor(data$surge_multiplier)
set.seed(42)
train_index <- createDataPartition(data$surge_multiplier, p = 0.7, list = FALSE)
train_data <- data[train_index, ]
test_data <- data[-train_index, ]
cat("Number of rows in train_data:", nrow(train_data), "\n")
cat("Number of rows in test_data:", nrow(test_data), "\n")
decision_tree <- rpart(surge_multiplier ~ ., data = train_data, method = "class")
rpart.plot(decision_tree, main = "Decision Tree for Surge Multiplier Prediction")
predictions <- predict(decision_tree, test_data, type = "class")
cat("Number of missing predictions:", sum(is.na(predictions)), "\n")
cat("Length of predictions:", length(predictions), "\n")
cat("Length of test_data surge_multiplier:", length(test_data$surge_multiplier), "\n")
conf_matrix <- confusionMatrix(predictions, test_data$surge_multiplier)
print(conf_matrix)
conf_matrix_sum <- sum(conf_matrix$table)
cat("Total count in confusion matrix:", conf_matrix_sum, "\n")
accuracy <- conf_matrix$overall['Accuracy']
precision <- conf_matrix$byClass['Pos Pred Value']
recall <- conf_matrix$byClass['Sensitivity']
f1_score <- 2 * (precision * recall) / (precision + recall)
cat("\nModel Evaluation Metrics for Surge Multiplier:\n")
cat("Accuracy: ", accuracy, "\n")
cat("Precision: ", precision, "\n")
cat("Recall: ", recall, "\n")
cat("F1 Score: ", f1_score, "\n")
pred_prob <- predict(decision_tree, test_data, type = "prob")
roc_curves <- lapply(levels(test_data$surge_multiplier), function(level) {
roc(test_data$surge_multiplier == level, pred_prob[, level])
})
colors <- c("red", "blue", "green")
plot(roc_curves[[1]], col = colors[1], main = "ROC Curves for Surge Multiplier Prediction")
for (i in 2:length(roc_curves)) {
plot(roc_curves[[i]], col = colors[i], add = TRUE)
}
legend("bottomright", legend = levels(test_data$surge_multiplier), col = colors, lwd = 2)
auc_values <- sapply(roc_curves, auc)
cat("\nAUC Values:\n")
print(auc_values)

if (!require(caret)) install.packages("caret")
if (!require(rpart)) install.packages("rpart")
if (!require(rpart.plot)) install.packages("rpart.plot")
if (!require(pROC)) install.packages("pROC")
if (!require(dplyr)) install.packages("dplyr")

library(caret)
library(rpart)
library(rpart.plot)
library(pROC)
library(dplyr)

data <- read.csv("rideshare_kaggle.csv", header = TRUE)
glimpse(data)

target_features <- c('hour', 'day', 'month', 'price', 'distance',
                     'latitude', 'longitude', 'temperature', 'apparentTemperature')

target_features <- target_features[target_features %in% names(data)]

data <- data %>%
  select(all_of(target_features), surge_multiplier) %>%
  na.omit()

data$surge_multiplier <- as.factor(data$surge_multiplier)

set.seed(42)
train_index <- createDataPartition(data$surge_multiplier, p = 0.7, list = FALSE)
train_data <- data[train_index, ]
test_data <- data[-train_index, ]

cat("Number of rows in train_data:", nrow(train_data), "\n")
cat("Number of rows in test_data:", nrow(test_data), "\n")

decision_tree <- rpart(surge_multiplier ~ ., data = train_data, method = "class")
rpart.plot(decision_tree, main = "Decision Tree for Surge Multiplier Prediction")

predictions <- predict(decision_tree, test_data, type = "class")

cat("Number of missing predictions:", sum(is.na(predictions)), "\n")
cat("Length of predictions:", length(predictions), "\n")
cat("Length of test_data surge_multiplier:", length(test_data$surge_multiplier), "\n")

conf_matrix <- confusionMatrix(predictions, test_data$surge_multiplier)
print(conf_matrix)

accuracy <- conf_matrix$overall['Accuracy']

precision <- conf_matrix$byClass[, "Pos Pred Value"]
recall <- conf_matrix$byClass[, "Sensitivity"]

precision[is.na(precision)] <- 0
recall[is.na(recall)] <- 0

f1_score <- 2 * (precision * recall) / (precision + recall)
f1_score[is.na(f1_score)] <- 0  # Handle divisions by zero

cat("\nModel Evaluation Metrics for Surge Multiplier:\n")
cat("Accuracy: ", accuracy, "\n")
cat("Precision for each class: \n")
print(precision)
cat("Recall for each class: \n")
print(recall)
cat("F1 Score for each class: \n")
print(f1_score)

avg_precision <- mean(precision, na.rm = TRUE)
avg_f1_score <- mean(f1_score, na.rm = TRUE)

cat("\nAverage Precision: ", avg_precision, "\n")
cat("Average F1 Score: ", avg_f1_score, "\n")

pred_prob <- predict(decision_tree, test_data, type = "prob")

roc_curves <- lapply(levels(test_data$surge_multiplier), function(level) {
  roc(as.numeric(test_data$surge_multiplier) == as.numeric(level), pred_prob[, level])
})

colors <- c("red", "blue", "green", "purple", "orange", "cyan", "magenta")
plot(roc_curves[[1]], col = colors[1], main = "ROC Curves for Surge Multiplier Prediction")

for (i in 2:length(roc_curves)) {
  plot(roc_curves[[i]], col = colors[i], add = TRUE)
}

legend("bottomright", legend = levels(test_data$surge_multiplier), col = colors, lwd = 2)

auc_values <- sapply(roc_curves, auc)
cat("\nAUC Values for each class:\n")
print(auc_values)